### PR TITLE
Feature/settings panel and xml

### PR DESCRIPTION
**Pull request by nalbion**
This is a work in progress, but welcome feedback as this is my first IntelliJ plugin.  I think the form would eventually have more options - maybe a separate panel for Recognition & TTS - locale, voice, credentials...

### CODE REVIEW

**Comment by breandan** [comment]
Nice idea to abstract over ASR/TTS providers! I should be able to review and accept these over the weekend. Thank you for contributing!

**Comment by nalbion** [comment]
I started on an AWS Lex ASR recognition implementation. Think an NLP abstraction is also required to convert a recognised string (and context) into actions.
For Lex and Google Voice API I think the ASR mic needs a Voice Activity Detector so that only the interesting audio snippets are sent. The current implementation saves 15 seconds of audio to disk, what happens when the voice command spans 2 connective recordings? Perhaps CustomMicrophone also needs a VAD?
-------- Original message --------From: breandan <notifications@github.com> Date: 6/7/17  11:35 pm  (GMT+10:00) To: breandan/idear <idear@noreply.github.com> Cc: Nicholas Albion <nalbion@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [breandan/idear] Feature/settings panel and xml (#36) 
Nice idea to abstract over ASR/TTS providers! I should be able to review and accept these over the weekend. Thank you for contributing!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/breandan/idear","title":"breandan/idear","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/breandan/idear"}},"updates":{"snippets":[{"icon":"PERSON","message":"@breandan in #36: Nice idea to abstract over ASR/TTS providers! I should be able to review and accept these over the weekend. Thank you for contributing!"}],"action":{"name":"View Pull Request","url":"https://github.com/breandan/idear/pull/36#issuecomment-313397858"}}}

**Comment by breandan** [comment]
Thanks, merged. If your project configuration gets corrupted after updating (it happened to me), you will need to remove all `.idea` related configuration files (or kill it completely `rm -rf idear && git clone https://github.com/OpenASR` if that fails) and `Import Project` as a Gradle project in IntelliJ IDEA.

**Comment by breandan** [comment]
FYI the [Minecraft Dev](https://github.com/minecraft-dev/MinecraftDev) project has some good examples of using the IntelliJ Platform SDK in Kotlin. Particularly the [settings implementation](https://github.com/minecraft-dev/MinecraftDev/blob/dev/src/main/kotlin/com/demonwav/mcdev/MinecraftConfigurable.kt). Kotlin has some language features to make things easier, ie. [late initialization](https://kotlinlang.org/docs/reference/properties.html#late-initialized-properties) lets us avoid using `!!` and `?`everywhere. I can handle the plugin API side going forward if you want to focus on integrating these providers.

**Pull request merged**
